-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 06, 2017 at 07:22 PM
-- Server version: 10.1.21-MariaDB
-- PHP Version: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `qa`
--

-- --------------------------------------------------------

--
-- Table structure for table `funding`
--

CREATE TABLE `funding` (
  `f_link` varchar(1000) NOT NULL,
  `f_desc` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `funding`
--

INSERT INTO `funding` (`f_link`, `f_desc`) VALUES
('https://yourstory.com/2017/02/softbank-wework/', 'Funding SoftBank may invest $3B in WeWork, signals rise of co-working spaces America-based co-working or shared work space provider WEWork is all set to raise $3 billion from SoftBank, at a valuation of $17-20 billion, say media reports. This is an interesting development as the company plans to expand globally and India is going to be a major focus market. India has nearly 30 co-working centres with […] Team YS 27 Feb 2017'),
('https://yourstory.com/2017/02/cartrade-funding-55-million/', 'Funding CarTrade raises $55M to fuel growth and acquisitions CarTrade, the online automobile classifieds platform, has raised $55 million from Singapore-based investment firm Temasek. The funding round also witnessed the participation of a large US family office. The capital will be utilised to support CarTrade’s growth plans through acquisitions, expansion into new areas such as auto finance, and to further sharpen its services to […] Team YS 08 Feb 2017'),
('https://yourstory.com/2016/10/putting-yourself-in-your-investors-shoes/', 'Funding Putting yourself in your investors’ shoes It’s very difficult to be an angel investor. I can relate to it because of the amount of time we as founders spend on our product and in hiring the right people for our team. If  it doesn’t turn out well after all that work, I know just how disappointing it is! You had been […] Siddhartha Ahluwalia 17 Oct 2016'),
('https://yourstory.com/2016/09/startup-hashtaag-raises-funding/', 'Funding Bengaluru-based startup Hashtaag laps up $1mn in angel funding Bengaluru-based startup Hashtaag, which builds native mobile apps and products, today announced it has secured $1 million in angel funding. The funding would enable the firm to hire better talent, build better products and expand operations further in India and globally. Krishna Vemula, Chairman and Co-Founder of Hashtaag, said, We intend to make rapid inroads […] Press Trust of India 22 Sep 2016'),
('https://yourstory.com/2016/09/bala-deshpande-valuations/', 'Funding All you wanted to know about valuations, but did not know who to ask Iska valuation mere valuation se zyada kaise? Startup founders are often found asking this to whoever cares to listen. The topic of valuations causes a lot of heartburn when a startup finds itself in the market for funding. When you have slogged over your product or service for months, and the investor does not place […] Dipti Nair 22 Sep 2016'),
('https://yourstory.com/2016/09/lucideus-tech-raises-funds/', 'Funding Cyber security service provider Lucideus Tech raises angel funding Cyber security service provider Lucideus Tech has received angel funding from Amit Choudhary, director of Motilal Oswal Private Equity Advisors. The startup, which was incubated by IIT-Bombay, had previously received funding from Anand Chandrasekaran (former Snapdeal Chief Product Officer) and Flipkart Chief Financial Officer Sanjay Baweja. It helps enterprises assess risks to their IT infrastructure. Lucideus […] Press Trust of India 01 Sep 2016'),
('https://yourstory.com/2016/08/innovaccer-funding/', 'Funding YourStory Tech30 2015 big data startup Innovaccer raises $15.6mn in Series A funding Silicon Valley-based Innovaccer has raised $15.6 million in Series A funding, led by Westbridge Capital Partners, with participation from other angel investors.  The big data platform will use the new capital to grow its footprint in healthcare. The company plans on enhancing its technology in big data and algorithms, which will help offer better outcomes at […] Sanghamitra Kar 11 Aug 2016'),
('https://yourstory.com/2016/08/looking-for-startup-funding/', 'Funding Looking for funding? Think again Riding on the stupendous wave of investment in Indian startups in 2015, many eager, fund-chasing, young entrepreneurs are yet to come to terms with reality. This year has seen a whole lot of changes in the way funds have been doled out and hitherto unseen down rounds in Indian startup investments were witnessed. The seven […] Jai Kumananthaa Raaja 09 Aug 2016'),
('https://yourstory.com/2016/08/san-francisco-startup-8tv/', 'Funding San Francisco-based startup 8TV steps into Indian market with $500k funding San Francisco-based startup 8TV has raised $500,000 funding (about Rs 3.34 crore) from investors including Redcliffe Capital Managing Partner Dheeraj Jain, Google executive Tidhar Carmeli and angel investor Thomas Korte. The company, which offers short-form video network for brands, is also supported by the US tech giant Amazon that has invested about $100,000 worth of […] Press Trust of India 08 Aug 2016'),
('https://yourstory.com/2016/08/prepare-seed-funding-startups/', 'Funding Preparation for Seed Funding by Startups The initial capital raised by any startup is called Seed Funding or a Seed Investment. In this form of funding, a stake in the company is offered to investors in exchange for their investment. Seed funding is required for many purposes like acquiring office space and other infrastructural facilities, hiring key personnel, development of a […] Sameer Rastogi 03 Aug 2016'),
('https://yourstory.com/2016/07/angel-funding-fy-16/', 'Funding VC funding might be down, but angel investments saw a rise of 62 pc in FY 16 On Tuesday, venture debt firm InnoVen Capital announced the release of the ‘India Angel Report 2016’, which analyses and puts across the investment trends of the major angel groups of the country. Although not comprehensive, Ajay Hattangdi, Group COO and CEO of InnoVen Capital, believes the report is an effort to highlight the key trends […] Tarush Bhalla 28 Jul 2016'),
('https://yourstory.com/2016/07/byndr-seed-funding/', 'Funding Mobile-based learning platform Byndr raises $700,000 in seed funding Launched in March 2015, Hyderabad-based Byndr, a mobile learning management platform, has raised $700,000 in seed funding from Ben Franklin Technology Partners, Education Design Studio, and a group of angel investors. The fresh funds will be used to expand sales and development. There will also be an increased focus on providing colleges with added administrative […] Sanghamitra Kar 27 Jul 2016'),
('https://yourstory.com/2016/07/tiyo-seed-funding/', 'Funding After bootstrapping for a year, Kolkata-based healthtech startup Tiyo raises seed funding Kolkata-based healthtech startup Tiyo, which was launched in May 2015 by Ranna Dutta, Sandip Bodak and Sunil Mishra, has raised $120,000 of angel funding, after being bootstrapped for almost a year. The round was led by veteran entrepreneurs from Middle East- Anish K and Ajith Nair, CEO iAdepto Global. The company has also closed its […] Sanghamitra Kar 27 Jul 2016'),
('https://yourstory.com/2016/07/pitching-startups-to-investors/', 'Funding 4 things to consider while pitching your startup to an investor “It is much easier to put existing resources to better use, than to develop resources where they do not exist.” – , business magnate, investor, political activist and author Raising funds for a business is possibly the single biggest stressor for any wise entrepreneur. On the other hand, many entrepreneurs feel that they know their business […] Akanksha Chauhan 25 Jul 2016'),
('https://yourstory.com/2016/07/treebo-series_b-funding/', 'Funding Bertelsmann leads Rs 112-crore Series-B funding in budget hotel chain Treebo Bengaluru-based Treebo Group of Hotels has raised Rs 112 crore in a Series-B funding round, led by Bertelsmann India Investments (BII). Existing investors including SAIF Partners and Matrix Partners India also participated in the round. The company plans to use the fresh round of funds for its expansion, to strengthen market outreach, and enhance its […] Sanghamitra Kar 22 Jul 2016'),
('https://yourstory.com/2016/07/equity-crowdfunding-p2p-lending-space-india/', 'Funding The burgeoning equity crowdfunding and P2P lending space in India The crowdfunding industry has witnessed a massive growth globally. According to an industry report published by Massolution, the estimated fundraising volume through crowdfunding globally in 2015 was $34 billion. The industry has witnessed exponential growth from a mere $2.7 billion in 2012. Source: Crowdexpert.com When we talk about crowdfunding we generally refer to reward-based, donation-based […] Ajay Mittal 22 Jul 2016'),
('https://yourstory.com/2016/07/dogsee-chew-funding/', 'Funding Bengaluru-based Dogsee Chew secures Rs 2 cr angel funding Bengaluru-based dog food company ‘Dogsee Chew’ has raised Rs 2 crore in an angel round from Renu Balyan, a Delhi-based angel investor, who is a pet parent herself and an avid animal lover, and Jyotsna Bapat, an Associate Professor at IIIT Bangalore. The startup, founded in October 2015, is currently present in 20 states. The […] Sanghamitra Kar 21 Jul 2016'),
('https://yourstory.com/2016/07/make-crowdfunding-easy/', 'Funding Five steps to make crowdfunding easy Crowdfunding holds great potential for startup funding. However, since equity crowdfunding is not legal in India, this post is aimed to explore donation- and rewards-based crowdfunding. A study commissioned by the World Bank says that the global crowdfunding market could reach between $90 billion and $96 billion by 2025, roughly 1.8 times the size of […] Ajay Mittal 12 Jul 2016'),
('https://yourstory.com/2016/07/winters-funding-season/', 'Funding Through the ‘winters’ of funding season, an entrepreneurial journey In my early days as an aspiring entrepreneur, I saw founders of companies who managed to raised funds as heroes. They had valour to win battles and treaded a challenging path of building to-be-great companies. And so are the young entrepreneurs today. They work day in and day out, assembling brilliant teams, working out of […] Shubham Jain 11 Jul 2016'),
('https://yourstory.com/2016/07/overcart/', 'Funding Overcart raises $3 mn Series A funding from JSW Ventures, Omidyar Network, Sattva Capital and Venture Works Overcart, a marketplace for over-stocked, unboxed, refurbished and pre-owned products, has raised $3 million in Series A funding from JSW Ventures, Omidyar Network, Sattva Capital and Venture Works. In 2014, the startup had raised funds from K Ganesh’s Growthstory, The Phoenix Fund, Snow Leopard Ventures and GSF Superangels. The company plans to invest the fresh […] Aparajita Choudhury 08 Jul 2016'),
('https://yourstory.com/2016/07/investing-media-junk-traditional-models/', 'Funding Investing in media? Junk traditional models The business of media, especially news media, is a curious one. You wield a lot of power, but often the economics of running the business is tricky. It is a business that delivers above-normal returns to the top 2-3 players, and practically nothing to the rest. The reason is that success is dependent on the […] Koreel Lahiri 07 Jul 2016'),
('https://yourstory.com/2016/06/wipro-ventures-tlv-partners/', 'Funding Wipro Ventures invests undisclosed amount in Israeli VC firm TLV Partners India’s third largest software services exporter Wipro has invested an undisclosed amount in Israel-based venture capital firm TLV Partners through its investment arm Wipro Ventures. This marks Wipro’s first investment in a venture capital firm. The move potentially gives the outsourcing firm access to a portfolio of early-stage enterprise and security ventures in one of […] News Desk 25 Jun 2016'),
('https://yourstory.com/2016/06/cuemath-funding/', 'Funding Bengaluru-based edtech startup Cuemath raises $4M funding from Sequoia Capital Bengaluru-based edtech startup Cuemath has raised $4 million in Series A funding from Sequoia India and existing investor Unitus Seed Fund to expand its home-based math learning network in India and international markets. It had raised Rs one crore seed fund from United Seed Fund in 2014. Cuemath offers a technology platform for women to […] Aparajita Choudhury 07 Jun 2016'),
('https://yourstory.com/2016/05/startup-pitches/', 'Funding How to pitch right to raise funding “Hitting is timing. Pitching is upsetting timing,” said Pitcher Warren Spahn once, just once. This quote from Baseball’s Hall of Fame legend essentially has a one-word takeaway for startup pitchers: timing. Whether it’s arriving on-time to pitch, the time one takes to pitch or knowing when one’s time has really come. As you would have […] Vinay Dora 24 May 2016'),
('https://yourstory.com/2016/05/purplehealth-funding/', 'Funding Thiruvananthapuram-based PurpleHealth raises $100k funding from Katabole Technology Venture Thiruvananthapuram-based on-demand health platform PurpleHealth has raised $100,000 from tech investor Katabole Technology Venture. The fresh funds will help the startup build collaborative healthcare distribution models with a common customer pool, through integrated technology. Founded in 2014 by Vikram Nair, Prakash Sathyapalan and Mini Balaraman, PurpleHealth is a 360-degree health and wellness platform that delivers a diverse […] Aparajita Choudhury 18 May 2016'),
('https://yourstory.com/2016/05/idgvi-digital-consumer-innovators/', 'Announcements IDG Ventures India looking to back consumer tech & digital media startups IDG Ventures India has launched a Digital Consumer Innovators programme to provide assistance to startups across consumer internet and digital media space, including Digital Content / Video / Entertainment, Vernacular / Local languages, content-led commerce models Team YS 13 May 2016'),
('https://yourstory.com/2016/05/shashank-murali-tapchief-vijay-shekhar-sharma-ideathon/', 'Funding How a unicorn founder backed us in 5 minutes Fred Wilson, a popular VC in the US,displays this(see the image on the right) cereal box in a conference room at his office. For the uninitiated, this is one of the 1,000 cereal packets that Brian Chesky and his co-founders sold during the 2008 Democratic convention to raise $30,000 for Airbnb. It was a growth […] Shashank Murali 12 May 2016'),
('https://yourstory.com/2016/04/how-raise-money-startup/', 'Funding Trying to raise money for your startup? What can go wrong? The Uphill Task Of Raising Money A lot of startups die at the inception stage itself. There is definitely a need for that capital and getting it is a Herculean task. Easier said than done, but a lot of startups are unable to sell their value proposition to investors effectively. Moreover, with investors being very […] Sukirti Sharma 20 Apr 2016'),
('https://yourstory.com/2016/04/driverskart-funding/', 'Funding Chennai-based DriversKart raises pre-Series A funding from ah! Ventures, Namit Agarwal and others Chennai-based DriversKart, an on-demand driver solution provider, has raised an undisclosed amount in pre-Series A round of funding from ah! Ventures. The round also saw the participation of Sidharth Pansari, Apurva Salarpuria, Saket Agarwal and Ayush Patni, Silicon Valley investors, and Namit Agarwal. The funds raised will be utilised for technological enhancement, enhanced driver on-boarding/training, […] Aparajita Choudhury 19 Apr 2016'),
('https://yourstory.com/2016/04/things-should-think-on-investment/', 'Funding 5 things entrepreneurs should think about when seeking investment Seeking investment is a constant battle for the entrepreneur. But if it’s the first time, the entrepreneur needs to work on finding answers to some crucial questions like what about the business makes it attractive to an investor. What scares an investor away? What should be in place in order to make the business attractive […] Karl Alomar 18 Apr 2016');

-- --------------------------------------------------------

--
-- Table structure for table `marketing`
--

CREATE TABLE `marketing` (
  `m_link` varchar(1000) NOT NULL,
  `m_desc` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `marketing`
--

INSERT INTO `marketing` (`m_link`, `m_desc`) VALUES
('https://www.entrepreneur.com/article/290920', 'Boost Facebook Engagement With These 3 Psychology Principles'),
('https://www.entrepreneur.com/article/291010', 'Marketers and Agencies Should be Unified and Not Siloed'),
('https://www.entrepreneur.com/article/291007', 'How Snapchat Is Contributing To Brand Recognition And Loyalty'),
('https://www.entrepreneur.com/article/290831', 'How Targeted Marketing Can Improve Your Brand\'s Efficiency'),
('https://www.entrepreneur.com/article/290766', '4 Ways Brick-and-Mortar Stores Can Outsell Online Retailers'),
('https://www.entrepreneur.com/article/290785', '7 Mobile Trends Every Small Business Should Follow This Year'),
('https://www.entrepreneur.com/video/288604', 'What Happened When I Test Drove a $350,000 Bentley Mulsanne'),
('https://www.entrepreneur.com/article/290887', 'How to Optimize Your Product Online'),
('https://www.entrepreneur.com/article/290745', 'How to Create a Successful Influencer Marketing Campaign'),
('https://www.entrepreneur.com/article/290451', '4 Things Your Website Needs Convert Visitors Into Customers'),
('https://www.entrepreneur.com/article/290400', '10 Top Live Video Influencers to Follow'),
('https://www.entrepreneur.com/article/290731', 'The Death of Traditional Advertising and the Rise of Originality'),
('https://www.entrepreneur.com/article/290899', '#5 Key Pointers to Know When You Bootstrap Your Digital Marketing Startup'),
('https://www.entrepreneur.com/article/286259', 'How to Handle Negative Comments and Keep Your E-Commerce Customers Happy'),
('https://www.entrepreneur.com/article/287145', 'How to Build Buzz and Launch Your Company');

-- --------------------------------------------------------

--
-- Table structure for table `news`
--

CREATE TABLE `news` (
  `news` varchar(1000) NOT NULL,
  `newslink` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `news`
--

INSERT INTO `news` (`news`, `newslink`) VALUES
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNFYc4zIkLa1wgoxLI7zBtS9OfrhsQ&clid=c3a7d30bb8a4878e06b80cf16b898331&cid=52779128123731&ei=vGFVV6iwMYvu4QKy5qjoBw&url=http://techcircle.vccircle.com/2016/06/06/meet-the-five-startups-selected-for-oracles-accelerator-programme/', 'Meet the five startups selected for Oracle\'s accelerator programme'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNGcLyPWpqipKOOY35WjbuPL7p_bZQ&clid=c3a7d30bb8a4878e06b80cf16b898331&cid=52779128007187&ei=vGFVV6iwMYvu4QKy5qjoBw&url=http://yourstory.com/2016/06/sillymonks-funding/', 'Multi-channel network SillyMonks raises Rs 3cr funding from an HNI, plans to launch 6 web series properties'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNHEcSQ3Vuvkn5VPYkKF5DGQJkTO3Q&clid=c3a7d30bb8a4878e06b80cf16b898331&cid=52779127929316&ei=vGFVV6iwMYvu4QKy5qjoBw&url=http://www.iamwire.com/2016/06/marketwire-1-250-startup-india-applications-cleared/137551', '#MarketWire: Only 1 Out of 250 Startup India Applications Cleared & More'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNHAsGXVqLQf28T1ch2I95TYcuxmNA&clid=c3a7d30bb8a4878e06b80cf16b898331&ei=vGFVV6iwMYvu4QKy5qjoBw&url=http://www.newindianexpress.com/states/telangana/KTR-evinces-interest-in-Clean-Tech-Incubator/2016/06/06/article3468350.ece', 'KTR evinces interest in Clean Tech Incubator'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNHsvxqdTuFrGLk03QsqMSVfuEwzAA&clid=c3a7d30bb8a4878e06b80cf16b898331&cid=52779125370285&ei=vWFVV8jtJ4vu4QKy5qjoBw&url=http://www.vccircle.com/news/technology/2016/06/02/home-salon-services-startup-pamperazi-merge-hyderabad-based-rival-zapluk', 'Home salon services startup Pamperazi to merge with Hyderabad-based rival ZapLuk'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNEjS4_YlJ_yc_FFmKfbDsx9x_w4Jg&clid=c3a7d30bb8a4878e06b80cf16b898331&cid=52779122907167&ei=vGFVV6iwMYvu4QKy5qjoBw&url=http://yourstory.com/2016/05/hyderabad-angels-investments/', 'Hyderabad Angels invested Rs 15cr in 12 startups last year, looks at 12 more this year'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNEyicqtdnQLOhtYzzlulHH0Ys4FWQ&clid=c3a7d30bb8a4878e06b80cf16b898331&cid=52779120825261&ei=vGFVV6iwMYvu4QKy5qjoBw&url=http://www.newindianexpress.com/cities/hyderabad/IIIT-Hyderabad-to-fund-three-innovative-startups/2016/05/28/article3454860.ece', 'IIIT-Hyderabad to fund three innovative startups'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNGyPaivWCVKtsawdD6V8mDB5q0Hdg&clid=c3a7d30bb8a4878e06b80cf16b898331&cid=52779119270495&ei=htNHV5DxHs214ALg9oPwDQ&url=http://yourstory.com/2016/05/driven-startup-story/', 'This startup lets you get behind the wheel of a BMW or Audi car even if you don\'t own one'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNHWkvEGHtoS3bUUfMGT40iLeM-Owg&clid=c3a7d30bb8a4878e06b80cf16b898331&ei=htNHV5DxHs214ALg9oPwDQ&url=http://yourstory.com/2016/05/capillary-technologies-growth/', 'With 500 million transactions a year, Capillary Technologies targets to be cash positive by the end of 2016'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNGxYmbhvVA1hTMwi_zmXkR1_cKpmw&clid=c3a7d30bb8a4878e06b80cf16b898331&cid=52779114038813&ei=hdNHV7iNLdTT4QLMmIrQBw&url=http://tech.firstpost.com/news-analysis/how-a-young-it-minister-is-transforming-hyderabad-into-a-global-business-city-once-again-316457.html', 'How a young IT minister is transforming Hyderabad into a global business city once again'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNGuVf_OT04x0EoU5ueJgyNG2bAGuQ&clid=c3a7d30bb8a4878e06b80cf16b898331&ei=8ZJCV6jFKsGs8AXvs7mIBA&url=http://tech.firstpost.com/startup/hyderabad-based-startup-ibot-aims-at-driving-iot-led-innovation-for-indian-businesses-315028.html', 'Hyderabad-based startup iBot aims at driving IoT-led innovation for Indian businesses'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNGhFI6ShxQBSASSX0ijsgJ2BdeaGg&clid=c3a7d30bb8a4878e06b80cf16b898331&cid=52779109175806&ei=m6U6V-DaAYKv4ALB5JDwAg&url=http://www.business-standard.com/article/pti-stories/hyderabad-to-host-next-edition-of-campus-party-116051600711_1.html', 'Hyderabad to host next edition of \'Campus Party\''),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNFBkUV6k2-tQ_6eHPYDA9qoQ7PwAg&clid=c3a7d30bb8a4878e06b80cf16b898331&cid=52779107664252&ei=nKU6V9iPDZWI4gKvpYegBQ&url=http://www.newindianexpress.com/cities/hyderabad/From-apps-that-assist-parking-in-malls-to-saving-water-ideas-burst-at-hackathon/2016/05/15/article3433649.ece', 'From apps that assist parking in malls to saving water, ideas burst at hackathon'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNEWmzj6TlO-_v5HQDmehFjjRGrDxg&clid=c3a7d30bb8a4878e06b80cf16b898331&ei=nKU6V9iPDZWI4gKvpYegBQ&url=https://inc42.com/buzz/funding-galore-93/', 'Funding Galore: Startup Fundings Of The Week [9 May – 14 May]'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNEqhSeJ7L9YpsmYxDhoxZeU6Q5Q_g&clid=c3a7d30bb8a4878e06b80cf16b898331&cid=52779104453250&ei=DGg1V-CsOsWW4gLGpoTQCg&url=http://yourstory.com/2016/05/life-circle-funding/', 'T-Hub incubatee Life Circle raises $150000 from Europe-based healthcare service provider, GROUPE SOS'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNGsY4t-c6GmZX3mMJ_CP_SAUUfYqQ&clid=c3a7d30bb8a4878e06b80cf16b898331&cid=52779105858759&ei=AIg1V9jKI56a4gL-wLyQDQ&url=http://tech.economictimes.indiatimes.com/news/startups/iot-startup-einsite-raises-seed-round-from-kpcb-edge/52248874', 'IoT startup Einsite raises seed round from KPCB Edge'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNHvh86cGWM5yAcFr9ik6iodSNkGbQ&clid=c3a7d30bb8a4878e06b80cf16b898331&ei=rgQzV7jMGIy_8QX3r6eACw&url=http://www.forbes.com/sites/annefield/2016/05/10/weather-proofing-small-farmers-in-india/', 'Weather-Proofing Small Farmers In India'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNH0_MHRO2uj4G0Z2IbO1CPsXCmBlg&clid=c3a7d30bb8a4878e06b80cf16b898331&cid=52779103276338&ei=AYg1V9CpIZWI4gKvpYegBQ&url=http://techcircle.vccircle.com/2016/05/10/online-food-ordering-platform-swiggy-raises-7-mn/', 'Online food ordering platform Swiggy raises $7 mn'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNEr1DzSwcx8s7I8NX8dR6On8d6c-A&clid=c3a7d30bb8a4878e06b80cf16b898331&cid=52779103514462&ei=rgQzV7jMGIy_8QX3r6eACw&url=http://tech.economictimes.indiatimes.com/news/startups/us-based-travel-tripper-opens-office-in-hyderabad/52200377', 'US-based Travel Tripper opens office in Hyderabad'),
('http://news.google.com/news/url?sa=t&fd=R&ct2=in&usg=AFQjCNGfLarpZLM-2dPT0E2s7X7wGfxVhA&clid=c3a7d30bb8a4878e06b80cf16b898331&ei=SX4xV_jgJoS68wX_0Y6oBw&url=http://www.newindianexpress.com/cities/hyderabad/IIT-H-centre-to-train-healthcare-innovators/2016/05/10/article3424857.ece', 'IIT-H centre to train healthcare innovators');

-- --------------------------------------------------------

--
-- Table structure for table `yourstory`
--

CREATE TABLE `yourstory` (
  `story_title` varchar(1000) NOT NULL,
  `story_link` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `yourstory`
--

INSERT INTO `yourstory` (`story_title`, `story_link`) VALUES
('https://yourstory.com/2017/03/revised-fund-of-funds-guidelines-dipp/', 'Start Up India Revised Fund of Funds guidelines will double startup funding: DIPP According to the Startup India Action Plan status report, Rs 500 crore out of Rs 10,000 corpus has been released to SIDBI (the fund manager of ‘Fund of Funds for Startups’) in FY 2015-16 and an additional Rs 100 crore will be released in FY 2016-17. Since the government announced the approval of the Rs 10,000-crore […] Aparajita Choudhury 30 Mar 2017'),
('https://yourstory.com/2017/03/what-stayzillas-battle-means-for-startup-world/', 'News The 12-day battle of Stayzilla and what it means to the startup world These 12 days have been eye-opening for startups and the startup ecosystem on how there is a need for strong systems that help founders shut operations peacefully, without being easy targets. It has been 12 days since Yogendra Vasupal, the Founder of Stayzilla, was taken into custody by the police. However, unlike most arrests, Yogendra’s […] Sindhu Kashyap 27 Mar 2017'),
('https://yourstory.com/2017/03/startup-nation/', 'Startup Lessons from Israel, the Startup Nation, for India While the Indian startup ecosystem has come a long way in the last five years, and the government has been doing its bit through programmes such as Startup India, there is still clearly a long way to go! This is an entrepreneur’s Aankho Dekhi perspective on what Startup India and Indian startups can take in […] Anish Basu Roy 27 Mar 2017'),
('https://yourstory.com/2017/03/stayzillas-yogendra-vasupal/', 'In Depth The Ides of March strikes Stayzilla’s Yogendra Vasupal with vodoo and criminal proceedings The startup world was shaken up today when Yogendra Vasupal of Stayzilla (that shut down recently) was arrested late last night in Chennai for fraud. But as YourStory found out, there’s more than meets the eye. It is 9:45 pm, a day before the Ides of March. A startup founder is produced before a magistrate in […] Sindhu Kashyap 15 Mar 2017'),
('https://yourstory.com/2017/03/andhra-pradesh-fintech-valley/', 'Stories Why the Andhra Pradesh government is betting big only on fintech “Focus. Focus. Focus,” said a rather resolute JA Chowdary, Special Chief Secretary and IT Advisor to the Andhra Pradesh Chief Minister, on the first day of Fintech Spring Conference 2017, held in Vishakhapatnam. The focus he talked about is one of the foundation stones of Andhra Pradesh’s new startup initiative, Fintech Valley Vizag. The flagship […] Tarush Bhalla 10 Mar 2017'),
('https://yourstory.com/2017/03/odisha-set-attract-startups-entrepreneurs-incentives-policy-changes-investments/', 'Events Odisha set to attract more startups, entrepreneurs with incentives, policy changes and investments After a comparatively slow start, Odisha is now taking giant leaps towards the development of a vibrant and dynamic startup ecosystem in the state. Several proposed changes to the existing Odisha Startup Policy 2016 will make it extremely lucrative for young entrepreneurs to start up in the state. From a sustenance allowance of INR 20,000 […] Hindol Goswami 09 Mar 2017'),
('https://yourstory.com/2017/03/facebook-launches-sheleadstech-programme-to-help-women-entrepreneurs/', 'Conferences Facebook launches SheLeadsTech programme to help women entrepreneurs overcome barriers and build successful tech startups Four out of five women in India want to start their own businesses. Unfortunately, the conversion rate is not high. Rampant gender bias and, more importantly, the lack of investor confidence because of preconceived notions that women’s primary focus is on their family, and that they aren’t as committed to their job as men, are […] Tanvi Dubey 09 Mar 2017'),
('https://yourstory.com/2017/03/benefits-of-registering-for-the-startup-india-learning-programme/', 'Start Up India 7 benefits of registering for the Startup India learning programme India is the third largest startup spot in the world, according to a report by NASSCOM and Zinnov. Across sectors, the number of startups are mushrooming. These not only encourage innovation and lead to job creation, but also positively impact the socio-economic fabric of our country. In an attempt to develop an ecosystem that promotes […] Deepika Singhania 09 Mar 2017'),
('https://yourstory.com/2017/03/startup-india-learning-programme-aims-to-make-entrepreneurship-resources-accessible/', 'E-Learning With 32K registered users a month, the Startup India Learning Programme aims to make entrepreneurship resources accessible to beginners Thirty-two thousand users from 600 Indian cities and over 30 countries. These are the numbers chalked up by the Startup India Learning Programme in just a month since it was launched. The free online entrepreneurship programme, a joint initiative by UpGrad, InvestIndia, and the Ministry of Industry and Commerce, is aimed at aspiring and emerging […] Sindhu MV 01 Mar 2017'),
('https://yourstory.com/2017/02/make-in-india-shailendra-singh/', 'News Thousand world-class incubators will take the Indian startup ecosystem forward: Shailendra Singh, DIPP The ‘Startup India’ initiative, launched in January 2016 by Prime Minister Narendra Modi, recently completed one year of existence. Shailendra Singh, Joint Secretary and CVO (Chief Vigilance Officer) at Department of Industrial Policy and Promotion (DIPP), took the stage at the Make in India – Karnataka conference to talk about the journey so far, learnings, […] Harshith Mallya 17 Feb 2017'),
('https://yourstory.com/2017/02/budget-2017-startups-impact/', 'Analysis Budget 2017: Decoding the impact on startups In the backdrop of demonetisation, with polls due in five states — including the highest populated state of Uttar Pradesh, and a lot of expectations from the across the globe, Finance Minister Arun Jaitley presented the Budget today. Imaginations were running wild — would this be a populist Budget or more in line with the […] Alok Patnia 02 Feb 2017'),
('https://yourstory.com/2017/01/startup-india-budget/', 'In Depth Startup India: Can the Budget make it stand up and be counted? With the aim of boosting entrepreneurship in the country, Prime Minister Narendra Modi in 2016 launched the Startup India campaign. What followed was a series of action plans, tax breaks, simplified compliances, and state sops targeted at making India a “Startup Hub”. As recent as December 2016, the government released a status report (released by […] Sriram Ramaswamy 31 Jan 2017'),
('https://yourstory.com/2017/01/india-adopt-policies-level-playing-field-internet-companies/', 'Opinion Should India adopt policies to level the playing field for Internet companies In 1835, Charles Darwin went to Galapagos, leading to his theory of evolution. In the Galapagos, there are no predators. As a result, a whole different kind of species have evolved — Marine iguana, Galápagos tortoise, Flightless cormorant, Great frigatebird. The animals and birds there are bereft of the fight-or-flight syndrome, that defines the animal […] Vani Kola 31 Jan 2017'),
('https://yourstory.com/2017/01/startup-india-initiative/', 'Opinion The Startup India initiative – a very long way to go It has been a year now since Prime Minister Narendra Modi launched the Startup India scheme on the 16th of January, 2016. However, the response to the scheme has been lukewarm.  As per certain media reports, less than 1,500 startups have so far applied for registration under the scheme, around 500 were recognised as startups, […] Alok Patnia 27 Jan 2017'),
('https://yourstory.com/2017/01/talocity-ketan-dewan/', 'Startup Talocity makes hiring easy by helping recruiters screen potential candidates through video CVs Talocity works as a one-stop shop for job seekers and recruiters by making the process of giving interviews, screening, and analysis easier. For 36-year-old Sushant Patil, who was between jobs, the daily hassle of finding companies hiring, and commuting to job interviews was getting cumbersome. Not only was the task of travel time-consuming, it also […] Sindhu Kashyap 24 Jan 2017'),
('https://yourstory.com/2017/01/startup-ecosystem-budget-expectation/', 'Trends A wary and disillusioned startup ecosystem looks for tax rebates and policy clarity in this year’s Budget As we move closer to this year’s Budget, the enthusiasm of the startup community is less than lukewarm. Compared to last year’s fanfare, this year, startups are wary and are waiting to see whether the Budget will really help them or not. It is that time of the year again. The 2017 Budget is right […] Sindhu Kashyap 23 Jan 2017'),
('https://yourstory.com/2017/01/startup-india-learning-program-offers-free-online-entrepreneurship-course/', 'News Startup India Learning Program offers free online entrepreneurship course On January 15, when the entire ecosystem gathered in New Delhi on the occasion of Startup India’s first anniversary, entrepreneur Ronnie Screwvala announced the launch of a learning and development programme. Developed by Invest India in collaboration with UpGrad, the Startup India Learning Program is meant to help entrepreneurs get their ideas and ventures to […] Tausif Alam 20 Jan 2017'),
('https://yourstory.com/2017/01/sidbi-ties-up-with-lic/', 'News SIDBI ties up with LIC for capital support to enterprises The Small Industries Development Bank of India (SIDBI) today said that it has tied up with the Life Insurance Corporation of India (LIC) for augmenting capital support to enterprises in the country. The idea behind tying up with the state-run insurance behemoth is to give a boost to the venture capital ecosystem for MSMEs, it […] Press Trust of India 06 Jan 2017'),
('https://yourstory.com/2016/12/startup-india-a-year-on/', 'In Depth A year since launch, is Startup India yet to take off? The supposed beneficiaries of Startup India have been left in limbo. A lack of clarity in the programme’s procedures, as well as mundane restrictions, has led to a good deal of disillusionment. Dr Harmitsingh Sikh, Founder and CEO of FoodMemories, applied for the SIDBI fund through the Entrepreneurship Development Institute of India (EDII) in May this […] Vishal Krishna 21 Dec 2016'),
('https://yourstory.com/2016/12/amitabh-kant-tie-global-summit/', 'Events A look back at how Startup India fared this year “You will never get an opportunity to ask questions directly. Ask and grill as much as you can,” said Amitabh Kant, CEO NITI Ayog, during a TiE Global Summit panel that was made up of people from Taxation, the Ministry of Electronics and Information Technology (MeitY), the Securities and Exchange Board of India (SEBI), and […] Sindhu Kashyap 18 Dec 2016'),
('https://yourstory.com/2016/12/women-entrepreneurs-trip-silicon-valley/', 'HerStory Meet the top 10 women entrepreneurs who won a trip to Silicon Valley The sixth edition of Women Entrepreneur Quest (WEQ) 2016, a contest for technology startups founded by women sponsored by Anita Borg Institute (ABI India) and the Department of Science and Technology (DST), Government of India, announced the top 10 women-led startups today. The announcement was made at the Anita Borg Institute’s annual conference in Bengaluru, the Grace Hopper […] Tanvi Dubey 09 Dec 2016'),
('https://yourstory.com/2016/12/amazon-launchpad-introduced-india/', 'News Amazon Launchpad introduced in India A year-and-a-half after launching it in the US, which was followed by its introduction in other Western countries, Amazon today introduced the Amazon Launchpad programme in India. The programme will help startups launch, market, and distribute their products to Amazon customers across India and around the world through a dedicated store. “This is the seventh […] Tausif Alam 05 Dec 2016'),
('https://yourstory.com/2016/11/rajiv-bansal-mobilesparks/', 'Mobisparks Govt will provide infrastructure but it’s startups who will build for masses – Rajiv Bansal If you thought that the government and bureaucrats do not engage in healthy debates with citizens, you certainly missed the keynote address by Rajiv Bansal, Joint Secretary, Department of Electronics and Information Technology, at the fifth edition of MobileSparks in Delhi today. Bansal, in his 30-minute session, shared the vision of Digital India with a room […] Alok Soni 18 Nov 2016'),
('https://yourstory.com/2016/10/q3-india-startup-funding-report/', 'Funding $3.5B poured into 815 deals in 9 months — an average of $13M invested per day in Indian startups Indian startups saw $3.5 billion angel and venture capital invested across over 815 deals between Q1-Q3 2016, representing a major decrease in the total deal value from the same period last year. According to YourStory Research, between January and September last year, $7.3 billion was invested across 639 deals. This year, while the number of […] Emmanuel Amberber 17 Oct 2016'),
('https://yourstory.com/2016/10/digging-deeper-into-tech30/', 'Report Digging deeper into Tech30 2016 Almost 3,000 startups applied to find a place in this year’s Tech30 list. Here’s a quick look at the ecosystem through the prism of TECH30 2016 applications. Nearly one-third of applications came from Bengaluru, followed by New Delhi/NCR (17%) and Mumbai (11%), Hyderabad (9%), Chennai (6%), with Kolkata and Pune accounting for 5% each.  The […] Emmanuel Amberber 17 Oct 2016'),
('https://yourstory.com/2016/10/chhattisgarh-startup-ecosystem/', 'Analysis Startup India, watch out for Chhattisgarh It is common for 24-year-old Shubhang, hailing from Raipur, to order from Flipkart or Amazon. It is convenient, he says. Shubhang’s is not an isolated case. “There are at least over a 1,000 orders that big national e-commerce players get from Raipur every day, and yet, ironically, there is a big problem of acceptance towards […] Sindhu Kashyap 14 Oct 2016'),
('https://yourstory.com/2016/09/startup-india-upgard/', 'News Startup India programme welcomes UpGrad as their education partner Online learning and education platform UpGrad is the official education partner for Centre’s ‘Startup India’ learning programme. Upgrad, co-founded by Ronnie Screwvala, will offer a four-week programme aimed at entrepreneurs looking to take the plunge or already 2-3 years into their journey, with the objective of exposing them to possible challenges in their entrepreneurial journey […] Press Trust of India 29 Sep 2016'),
('https://yourstory.com/2016/09/chattisgarh-kicks-off-its-startup-plans-to-boost-entrepreneurship-in-state/', 'News Now, Chattisgarh kicks off startup plans to boost entrepreneurship in State Prime Minister’s vision of Startup India gets a new fillip as the the Chattisgarh government recently launched ‘Start-up Chhattisgarh’ initiative to foster entrepreneurship and promote innovation. Talking at the event Chief Minister Raman Singh said that, Youths have no dearth of ideas. Lots of creative ideas take shape in their mind. They should convert them […] Press Trust of India 14 Sep 2016'),
('https://yourstory.com/2016/09/govt-invest-500cr-startups/', 'News Govt commits Rs 500cr for Narendra Modi’s Startup India vision, launches another set of initiatives While addressing the media in New Delhi, the Ministry of Science and Technology today announced the launch of the National Initiative for Development and Harnessing Innovations (NIDHI), an umbrella programme which aims to nurture ideas and innovations in the startup ecosystem. With the intent to speed up the process and also scale, the ministry will […] Sanghamitra Kar 07 Sep 2016'),
('https://yourstory.com/2016/09/solve-start-up-problem/', 'Startup Don’t just start up- please take time out to sort out the right problem Every day, we hear new startup stories, some are inspiring, some are disappointing and some just don’t make any sense, neither in terms of the usefulness of the product, nor in terms of being a worthwhile investment opportunity. It is a great thing to start up, and we must give it a try, but what […] Shitij Bahl 01 Sep 2016');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
